# 🔢 NumPy — Guía completa + ejercicios

**Para:** Borja
**Módulo:** 3 — Pandas / NumPy (adelanto)

> 📌 **Nota de contexto:** esto es Módulo 3 de tu hoja de ruta, así que vas con
> adelanto sobre Fundamentos. Úsalo a tu ritmo: como referencia ahora, o como
> repaso cuando llegues formalmente a este módulo.

**Lo que vas a entender al terminar este notebook:**

1. Qué problema resuelve NumPy y por qué las listas de Python no bastan.
2. Cómo crear arrays (a mano y automáticamente).
3. Cómo indexar y recortar arrays, en 1D y en 2D (filas y columnas).
4. Operaciones vectorizadas: hacer cálculos sobre arrays enteros sin bucles.
5. Broadcasting: combinar arrays de tamaños distintos.
6. Funciones de agregación y el parámetro `axis` (clave para analizar datos).
7. Filtrado con condiciones (boolean masking) y `np.where()`.
8. Cómo tratar datos faltantes (`NaN`).
9. Combinar y reordenar arrays.
10. Generar datos aleatorios para simulaciones.
11. Ejercicios progresivos, pensados como analista de datos.

Todo explicado primero con una analogía sencilla, y después con el detalle
técnico — siempre con el resultado real de ejecutar el código.


## 1. ¿Por qué existe NumPy?

**Qué es:** NumPy es una librería que añade un nuevo tipo de dato a Python, el
`array`, pensado específicamente para guardar muchos números y operar con todos
ellos a la vez, de forma muy rápida.

**Para qué sirve:** para hacer cálculos matemáticos sobre conjuntos enteros de
datos (una columna de ventas, una serie de temperaturas, una tabla de números)
sin tener que escribir un bucle `for` cada vez.

**Qué problema resuelve:** las listas de Python son geniales para guardar
cualquier cosa, pero son lentas para hacer matemáticas con muchos números, y
además **no se comportan como cabría esperar** cuando intentas operar con ellas
directamente.

### 🎈 Analogía sencilla

Imagina una bolsa con 1000 canicas y quieres multiplicar el tamaño de cada
canica por 2.

- Con una **lista de Python**, tienes que meter la mano, sacar una canica,
  multiplicarla, devolverla... canica por canica, 1000 veces (un bucle).
- Con un **array de NumPy**, es como tener una máquina especial: metes la bolsa
  entera y sale la bolsa entera ya multiplicada, en un solo movimiento.

### 🐍 Código Python: el mismo cálculo, con lista y con array


In [1]:
# Con una lista normal de Python necesitas un bucle (o una comprensión de lista)
ventas_lista = [120, 85, 200, 60, 150]
ventas_dobles_lista = [venta * 2 for venta in ventas_lista]

print("Lista original:", ventas_lista)
print("Lista doblada:", ventas_dobles_lista)


Lista original: [120, 85, 200, 60, 150]
Lista doblada: [240, 170, 400, 120, 300]


In [2]:
import numpy as np

# Con NumPy, el mismo cálculo se hace directamente sobre el array entero
ventas_array = np.array([120, 85, 200, 60, 150])
ventas_dobles_array = ventas_array * 2

print("Array original:", ventas_array)
print("Array doblado:", ventas_dobles_array)


Array original: [120  85 200  60 150]
Array doblado: [240 170 400 120 300]


### ⚠️ Error común (y muy importante): listas y arrays NO se multiplican igual

Esto sorprende a casi todo el mundo la primera vez:


In [3]:
lista = [1, 2, 3]
print("lista * 2 =", lista * 2)   # ¡Sorpresa!

array = np.array([1, 2, 3])
print("array * 2 =", array * 2)


lista * 2 = [1, 2, 3, 1, 2, 3]
array * 2 = [2 4 6]


`lista * 2` **no multiplica cada número**: repite la lista entera dos veces
(`[1, 2, 3, 1, 2, 3]`). En cambio, `array * 2` sí multiplica cada número
individualmente (`[2, 4, 6]`). Esta es, probablemente, la diferencia número uno
que hay que tener clarísima entre listas y arrays.

### 💼 Aplicación profesional

Cuando trabajes con miles o millones de filas de datos (por ejemplo, leyendo un
CSV de ventas), hacer un bucle `for` fila a fila es lento y poco profesional.
NumPy (y Pandas, que está construido encima de NumPy) hacen estos cálculos en
código C internamente, lo que los hace muchísimo más rápidos. Vamos a comprobarlo
con un caso más grande:


In [4]:
import time

cantidad = 2_000_000
numeros_lista = list(range(cantidad))
numeros_array = np.arange(cantidad)

inicio = time.time()
resultado_lista = [n * 2 for n in numeros_lista]
fin = time.time()
print("Tiempo con lista y bucle:", round(fin - inicio, 4), "segundos")

inicio = time.time()
resultado_array = numeros_array * 2
fin = time.time()
print("Tiempo con array de NumPy:", round(fin - inicio, 4), "segundos")


Tiempo con lista y bucle: 0.1754 segundos
Tiempo con array de NumPy: 0.0059 segundos


Los segundos exactos van a depender del ordenador donde lo ejecutes, pero la
proporción se mantiene: la versión con NumPy es muchísimo más rápida, y esa
diferencia se nota cada vez más cuantos más datos tengas.


## 2. Crear arrays y conocer sus atributos

**Qué es:** un array puede tener 1 dimensión (una fila de números, como una
columna de Excel) o 2 dimensiones (una tabla de filas y columnas, como una hoja
de cálculo entera).

### 🎈 Analogía sencilla

- Un array de **1 dimensión** es como una sola fila de casillas de un Excel.
- Un array de **2 dimensiones** es como una hoja de Excel completa: filas y
  columnas a la vez.

### 📊 Representación visual

```
Array 1D:           [ 120,  85, 200,  60, 150 ]

Array 2D (matriz):        col0  col1  col2
                fila0  [   120,   85,  200 ]
                fila1  [    60,  150,   90 ]
```

### 🐍 Código Python


In [5]:
# Array de 1 dimensión, a partir de una lista
ventas_1d = np.array([120, 85, 200, 60, 150])

# Array de 2 dimensiones, a partir de una lista de listas
ventas_2d = np.array([
    [120, 85, 200],
    [60, 150, 90],
])

print("Array 1D:")
print(ventas_1d)
print()
print("Array 2D:")
print(ventas_2d)


Array 1D:
[120  85 200  60 150]

Array 2D:
[[120  85 200]
 [ 60 150  90]]


In [6]:
print("Forma (shape) del 1D:", ventas_1d.shape)
print("Forma (shape) del 2D:", ventas_2d.shape)
print("Dimensiones (ndim) del 1D:", ventas_1d.ndim)
print("Dimensiones (ndim) del 2D:", ventas_2d.ndim)
print("Tipo de dato (dtype):", ventas_1d.dtype)
print("Número total de elementos (size):", ventas_2d.size)


Forma (shape) del 1D: (5,)
Forma (shape) del 2D: (2, 3)
Dimensiones (ndim) del 1D: 1
Dimensiones (ndim) del 2D: 2
Tipo de dato (dtype): int64
Número total de elementos (size): 6


### 🔍 Explicación línea a línea

- `np.array([...])` → convierte una lista (o lista de listas) en un array de
  NumPy. Es la forma más directa de crear uno a mano.
- `.shape` → te dice "cuántas filas y columnas tiene". Para el 1D, `(5,)`
  significa "5 elementos en una sola dimensión". Para el 2D, `(2, 3)` significa
  "2 filas, 3 columnas" — igual que dirías el tamaño de una tabla.
- `.ndim` → cuántas dimensiones tiene (1 para una fila suelta, 2 para una tabla).
- `.dtype` → de qué tipo son los números por dentro (`int64`, `float64`...). A
  diferencia de una lista de Python, **todos los elementos de un array tienen
  que ser del mismo tipo**.
- `.size` → cuántos números hay en total, sin importar la forma.

### ⚠️ Error común

Si mezclas listas de distinta longitud al crear un array 2D, NumPy no puede
formar una tabla rectangular y se queja (o, en versiones antiguas, te devuelve
algo raro). Una tabla siempre necesita que **todas las filas tengan el mismo
número de columnas**, igual que pasa en una hoja de Excel o una tabla SQL.

### 💼 Aplicación profesional

Piensa en un array 2D como una **tabla sin nombres de columna**: tiene filas y
columnas como una tabla SQL o un DataFrame de Pandas, pero sin las etiquetas. De
hecho, cuando más adelante uses Pandas, por debajo cada columna de un DataFrame
es, literalmente, un array de NumPy con una etiqueta puesta encima.


## 3. Generar arrays automáticamente

**Qué es:** funciones que crean arrays sin que tengas que escribir cada número
a mano.

**Para qué sirve:** para inicializar datos, crear secuencias, o generar escalas
de valores (por ejemplo, para el eje de un gráfico).

### 🎈 Analogía sencilla

Es como pedirle a alguien "rellena esta fila de 10 casillas con ceros", o
"dame los números del 1 al 10 de dos en dos", en vez de escribirlos tú uno a uno.

### 🐍 Código Python


In [7]:
print("zeros(5):", np.zeros(5))
print("ones(5):", np.ones(5))
print("arange(0, 10, 2):", np.arange(0, 10, 2))
print("linspace(0, 1, 5):", np.linspace(0, 1, 5))


zeros(5): [0. 0. 0. 0. 0.]
ones(5): [1. 1. 1. 1. 1.]
arange(0, 10, 2): [0 2 4 6 8]
linspace(0, 1, 5): [0.   0.25 0.5  0.75 1.  ]


### 🔍 Explicación línea a línea

- `np.zeros(5)` → un array de 5 ceros. Útil para "reservar espacio" antes de
  rellenarlo con datos reales.
- `np.ones(5)` → lo mismo, pero con unos.
- `np.arange(0, 10, 2)` → como el `range()` de Python que ya conoces (empieza en
  0, no llega a 10, salta de 2 en 2), pero te devuelve directamente un array.
- `np.linspace(0, 1, 5)` → "dame 5 números **igual de espaciados** entre 0 y 1,
  incluyendo ambos extremos". Es distinto de `arange`: tú decides *cuántos*
  números quieres, no de cuánto en cuánto saltar.

### 💼 Aplicación profesional

`arange` se usa mucho para generar índices o identificadores secuenciales.
`linspace` es muy habitual para crear escalas en gráficos (por ejemplo, el eje X
de una curva), algo que verás constantemente con Matplotlib más adelante.


## 4. Indexado y slicing (1D y 2D)

**Qué es:** acceder a uno o varios elementos de un array, igual que ya sabes
hacer con listas y con cadenas de texto — pero ahora también en 2 dimensiones.

### 🎈 Analogía sencilla

En un array 1D, es como señalar una casilla de una fila de Excel: "la casilla
número 2". En un array 2D, es como decir "la celda que está en la fila 1,
columna 2" — necesitas **dos** números para señalar una celda, igual que en
Excel dirías `B3` (columna B, fila 3).

### 📊 Representación visual

```
                col0  col1  col2
       fila0  [  120,   85,  200 ]
       fila1  [   60,  150,   90 ]

ventas_2d[1, 2] → fila 1, columna 2 → 90
ventas_2d[0, :] → toda la fila 0    → [120, 85, 200]
ventas_2d[:, 1] → toda la columna 1 → [85, 150]
```

### 🐍 Código Python


In [8]:
print("Elemento [0]:", ventas_1d[0])
print("Slice [1:3]:", ventas_1d[1:3])
print()
print("Elemento [1, 2]:", ventas_2d[1, 2])
print("Fila 0 completa:", ventas_2d[0, :])
print("Columna 1 completa:", ventas_2d[:, 1])


Elemento [0]: 120
Slice [1:3]: [ 85 200]

Elemento [1, 2]: 90
Fila 0 completa: [120  85 200]
Columna 1 completa: [ 85 150]


### 🔍 Explicación línea a línea

- `ventas_1d[0]` → el primer elemento, exactamente igual que con una lista.
- `ventas_1d[1:3]` → recorte (slice), igual que con listas y cadenas: del índice
  1 al 2 (sin incluir el 3).
- `ventas_2d[1, 2]` → **fila 1, columna 2**. Importante: el orden es siempre
  `[fila, columna]`, no al revés.
- `ventas_2d[0, :]` → fila 0, y los dos puntos `:` solos significan "todas las
  columnas".
- `ventas_2d[:, 1]` → todas las filas, columna 1. Aquí los dos puntos están en
  el lugar de la fila, así que significa "todas las filas".

### ⚠️ Error común

Confundir el orden: `ventas_2d[2, 0]` no es lo mismo que `ventas_2d[0, 2]`. El
primer número **siempre** es la fila, el segundo **siempre** es la columna.

### 💼 Aplicación profesional

Esto es exactamente lo que harás constantemente con Pandas para seleccionar
filas y columnas concretas de un DataFrame. Aprender bien `[fila, columna]` aquí
te va a ahorrar muchísima confusión luego con `.iloc[]`.


## 5. Operaciones vectorizadas

**Qué es:** aplicar una operación matemática a **todos** los elementos de un
array a la vez, con una sola línea, sin bucles.

### 🎈 Analogía sencilla

Si tienes dos filas de casillas (dos arrays del mismo tamaño) y las sumas, NumPy
suma **casilla con casilla**, en la misma posición — como sumar dos filas de una
hoja de Excel, celda a celda.

### 📊 Representación visual

```
   ventas_enero  = [ 120,  85, 200 ]
 + ventas_febrero= [  60, 150,  90 ]
   ───────────────────────────────
   total          = [ 180, 235, 290 ]
```

### 🐍 Código Python


In [9]:
ventas_enero = np.array([120, 85, 200])
ventas_febrero = np.array([60, 150, 90])

total = ventas_enero + ventas_febrero
diferencia = ventas_enero - ventas_febrero
doble = ventas_enero * 2
mitad = ventas_enero / 2

print("Total:", total)
print("Diferencia:", diferencia)
print("Doble de enero:", doble)
print("Mitad de enero:", mitad)


Total: [180 235 290]
Diferencia: [ 60 -65 110]
Doble de enero: [240 170 400]
Mitad de enero: [ 60.   42.5 100. ]


### 🔍 Explicación línea a línea

- `ventas_enero + ventas_febrero` → suma posición a posición: el primer número
  de enero con el primer número de febrero, el segundo con el segundo, etc.
- Lo mismo para resta, multiplicación y división: siempre **elemento a
  elemento**, no hace falta ningún bucle.

### ⚠️ Error común

Si los dos arrays no tienen el mismo tamaño, NumPy no sabe qué casilla
corresponde con cuál, y lanza un error:


In [10]:
array_corto = np.array([1, 2])
array_largo = np.array([1, 2, 3])

try:
    resultado = array_corto + array_largo
except ValueError as error:
    print("Error capturado:", error)


Error capturado: operands could not be broadcast together with shapes (2,) (3,) 


El mensaje habla de "formas que no se pueden combinar" (*broadcast*): NumPy no
puede emparejar 2 casillas con 3 casillas si no le dices cómo. Esto se conecta
directamente con lo siguiente: el *broadcasting*.

### 💼 Aplicación profesional

Esto es la base de cualquier cálculo de negocio sobre columnas: calcular el
margen (`precio_venta - precio_coste`), aplicar un descuento (`precio * 0.9`), o
sumar las ventas de dos meses, todo en una sola línea, sobre columnas enteras de
miles de filas. En SQL harías algo parecido con una operación entre columnas en
el `SELECT`; en DAX, sería una columna calculada.


## 6. Broadcasting: combinar arrays de tamaños distintos

**Qué es:** la forma en que NumPy combina arrays que no tienen exactamente el
mismo tamaño, "estirando" el más pequeño para que encaje con el más grande,
siempre que sea posible.

### 🎈 Analogía sencilla

Imagina que tienes una tabla de precios (varias filas y columnas) y quieres
aplicar el **mismo** IVA a todas las celdas. No necesitas escribir una tabla de
IVAs del mismo tamaño que la tabla de precios — le dices "aplica este único
número a todo", y NumPy se encarga de repetirlo donde haga falta.

### 📊 Representación visual

```
  precios (2x3)          IVA (un solo número)
[ 100,  50,  35 ]                                [ 121.0,  60.5, 42.35 ]
[  80,  20,  10 ]    *  (1 + 0.21)      =         [  96.8,  24.2, 12.1  ]
```

El número `1.21` no es una tabla — es un único valor que NumPy aplica a **cada**
celda de la tabla de precios.

### 🐍 Código Python


In [11]:
precios = np.array([
    [100, 50, 35],
    [80, 20, 10],
])

IVA = 0.21
precios_con_iva = precios * (1 + IVA)

print(precios_con_iva)


[[121.    60.5   42.35]
 [ 96.8   24.2   12.1 ]]


### 🔍 Explicación línea a línea

- `precios * (1 + IVA)` → `(1 + IVA)` es un único número (`1.21`). NumPy lo
  aplica a **cada** celda de la matriz `precios`, sin que tengas que crear una
  matriz de IVAs del mismo tamaño.

### ⚠️ Error común

El broadcasting no funciona con cualquier combinación de tamaños: solo cuando
las formas son compatibles según las reglas de NumPy (un escalar siempre
funciona; un array 1D puede combinarse con un 2D si el número de columnas
coincide). Si las formas no encajan de ninguna manera, obtendrás el mismo
`ValueError` que vimos en el punto anterior.

### 💼 Aplicación profesional

El broadcasting es lo que te permite aplicar una misma regla de negocio (un IVA,
una comisión, un descuento fijo) a una tabla entera de datos sin tener que
repetir ese valor manualmente en cada fila — exactamente igual que un parámetro
único reutilizado en una medida DAX o en una columna de Power Query.


## 7. Funciones de agregación y el parámetro `axis`

**Qué es:** funciones que resumen un array en un solo número (o en una fila/
columna de números): suma, media, máximo, mínimo, desviación estándar, mediana.

**Esto es probablemente lo más importante de todo el notebook para tu trabajo
como analista de datos**, porque es exactamente lo que hace un `GROUP BY` en
SQL, una medida en DAX, o los totales de una tabla pivote en Excel/Power BI.

### 🎈 Analogía sencilla

Imagina una hoja de Excel con productos en las filas y meses en las columnas.
Puedes pedir:

- El **total de cada fila** (cuánto vendió cada producto, sumando sus meses).
- El **total de cada columna** (cuánto se vendió en total cada mes, sumando
  todos los productos).

`axis` es justo eso: le dices a NumPy "suma recorriendo las filas" o "suma
recorriendo las columnas".

### 📊 Representación visual

```
                  enero  febrero  marzo     ← columnas (axis=1 recorre esto)
      Mesa     [   120,      85,    200 ]
      Silla    [    60,     150,     90 ]
      Lámpara  [    35,      20,     10 ]
         ↑
   filas (axis=0 recorre esto)

Total por producto (suma cada FILA)  → axis=1 → [405, 300, 65]
Total por mes      (suma cada COLUMNA) → axis=0 → [215, 255, 300]
```

> 💡 Truco para no confundirte (le pasa a todo el mundo al principio):
> `axis=0` significa "aplasta las filas, quédate con un resultado por columna".
> `axis=1` significa "aplasta las columnas, quédate con un resultado por fila".

### 🐍 Código Python


In [12]:
ventas = np.array([
    [120, 85, 200],   # Mesa
    [60, 150, 90],    # Silla
    [35, 20, 10],     # Lámpara
])

total_general = ventas.sum()
total_por_producto = ventas.sum(axis=1)
total_por_mes = ventas.sum(axis=0)

print("Total general:", total_general)
print("Total por producto (fila):", total_por_producto)
print("Total por mes (columna):", total_por_mes)


Total general: 770
Total por producto (fila): [405 300  65]
Total por mes (columna): [215 255 300]


In [13]:
print("Media de todas las ventas:", ventas.mean())
print("Venta máxima:", ventas.max())
print("Venta mínima:", ventas.min())
print("Desviación estándar:", round(ventas.std(), 2))
print("Mediana:", np.median(ventas))


Media de todas las ventas: 85.55555555555556
Venta máxima: 200
Venta mínima: 10
Desviación estándar: 59.32
Mediana: 85.0


### 🔍 Explicación línea a línea

- `ventas.sum()` (sin `axis`) → suma **todos** los números de la matriz, sin
  importar fila ni columna: un solo número.
- `ventas.sum(axis=1)` → un resultado **por fila** (recorre las columnas dentro
  de cada fila): el total de cada producto.
- `ventas.sum(axis=0)` → un resultado **por columna** (recorre las filas dentro
  de cada columna): el total de cada mes.
- `.mean()`, `.max()`, `.min()`, `.std()` funcionan exactamente igual,
  aceptando también `axis` si quieres el resultado por fila o por columna.
- `np.median(ventas)` → la mediana se llama como función (`np.median(...)`),
  no como método del array (`ventas.median()` no existe). Es una de las pocas
  excepciones que conviene recordar.

### ⚠️ Error común

Confundir qué eje resume cada `axis`. Si tu resultado tiene 3 números en vez de
los esperados, casi siempre es que has puesto `axis=0` cuando querías `axis=1`
(o al revés). El truco del recuadro de arriba ayuda a no perderse.

### 💼 Aplicación profesional

Esto es el equivalente exacto de:

- SQL: `SELECT producto, SUM(ventas) FROM tabla GROUP BY producto` (esto sería
  tu `axis=1`, un total por fila/producto).
- DAX: una medida `SUM(Ventas[Importe])` con un producto en el contexto de fila
  de una tabla visual.
- Excel/Power BI: los totales de fila y columna de una tabla pivote.

La diferencia es que aquí lo escribes en una línea de Python sobre una matriz
completa, en vez de en una herramienta visual.


## 8. Filtrado con condiciones (boolean masking) y `np.where()`

**Qué es:** seleccionar solo los elementos de un array que cumplen una
condición, sin necesidad de un bucle `if` recorriendo uno a uno.

### 🎈 Analogía sencilla

Imagina que le pasas un "filtro de luz" a una fila de casillas: las casillas
que cumplen la condición se quedan visibles, las que no, se descartan. Es
exactamente lo que hace un filtro de Excel o una cláusula `WHERE` de SQL, pero
sobre un array.

### 🐍 Código Python


In [14]:
ventas_dia = np.array([120, 45, 300, 80, 15, 250])

mascara = ventas_dia > 100
print("Máscara (True/False):", mascara)
print("Ventas que superan 100:", ventas_dia[mascara])


Máscara (True/False): [ True False  True False False  True]
Ventas que superan 100: [120 300 250]


### 🔍 Explicación línea a línea

- `ventas_dia > 100` → no filtra nada todavía: crea un array de `True`/`False`,
  uno por cada posición, indicando si esa posición cumple la condición.
- `ventas_dia[mascara]` → usar ese array de `True`/`False` como índice te
  devuelve **solo** los elementos donde había un `True`. Es exactamente un
  filtro, igual que un `WHERE ventas > 100` en SQL.

### 🐍 `np.where()`: elegir un valor u otro según la condición


In [15]:
etiquetas = np.where(ventas_dia > 100, "Alto", "Bajo")
print(etiquetas)


['Alto' 'Bajo' 'Alto' 'Bajo' 'Bajo' 'Alto']


### 🔍 Explicación línea a línea

- `np.where(condicion, valor_si_true, valor_si_false)` → recorre el array
  posición a posición y, para cada una, decide qué valor poner según si cumple
  la condición o no. Es el equivalente de un `IF` de Excel, un `CASE WHEN` de
  SQL, o un `IF()` de DAX, pero aplicado a todo el array de golpe.

### ⚠️ Error común

Olvidar que `mascara` no son los datos filtrados, sino solo el array de
`True`/`False`. Si imprimes `mascara` esperando ver `[300, 250]`, te vas a
encontrar con `[False, False, True, False, False, True]` — el filtrado real
ocurre al usar la máscara como índice (`ventas_dia[mascara]`), no antes.

### 💼 Aplicación profesional

El filtrado con condiciones es, literalmente, el `WHERE` de tus análisis: vas a
usarlo constantemente para quedarte solo con las filas que te interesan (ventas
de un cliente, productos por encima de un umbral, fechas dentro de un rango).
`np.where()` es tu herramienta para crear columnas calculadas con lógica
condicional, igual que harías con una columna calculada en Power Query o DAX.


## 9. Datos faltantes: `NaN`

**Qué es:** `NaN` (*Not a Number*) es el valor especial que NumPy usa para
representar "este dato no existe" — el equivalente a una celda vacía en Excel
o un `NULL` en SQL.

### 🎈 Analogía sencilla

Es como una casilla de un formulario que alguien dejó en blanco a propósito,
porque no tenía ese dato. No es un cero, no es un error: es "no lo sé / no
existe".

### 🐍 Código Python


In [16]:
ventas_con_huecos = np.array([120, 85, np.nan, 60, np.nan, 150])

print("Array con huecos:", ventas_con_huecos)
print("¿Cuáles son NaN?:", np.isnan(ventas_con_huecos))
print("Media normal (mal):", ventas_con_huecos.mean())
print("Media ignorando huecos (bien):", np.nanmean(ventas_con_huecos))


Array con huecos: [120.  85.  nan  60.  nan 150.]
¿Cuáles son NaN?: [False False  True False  True False]
Media normal (mal): nan
Media ignorando huecos (bien): 103.75


### 🔍 Explicación línea a línea

- `np.nan` → el valor especial que representa "falta este dato". Solo existe
  para números decimales (`float`), por eso el array entero pasa a ser de tipo
  `float` aunque metas enteros.
- `np.isnan(array)` → te dice, posición a posición, si ese valor es un hueco.
- `ventas_con_huecos.mean()` → ⚠️ si **cualquier** valor del array es `NaN`, el
  resultado de la media normal también es `NaN`. Un solo dato que falte
  "contamina" todo el cálculo.
- `np.nanmean(array)` → calcula la media **ignorando** los huecos, como si esas
  posiciones no existieran. Hay una versión "nan-" de casi todas las funciones
  de agregación: `np.nansum()`, `np.nanmax()`, `np.nanstd()`...

### ⚠️ Error común

Usar `.mean()` directamente sobre datos reales (que casi siempre tienen huecos)
y no entender por qué el resultado es `NaN`. Si tu media sale `nan`, lo primero
que hay que comprobar es si hay datos faltantes sin tratar.

### 💼 Aplicación profesional

Tratar datos faltantes es una de las tareas más habituales de limpieza de
datos. En Pandas verás esto constantemente como `.isna()`, `.dropna()` o
`.fillna()` — todo ello construido sobre esta misma idea de NumPy.


## 10. Reorganizar y combinar arrays

**Qué es:** cambiar la "forma" de un array sin cambiar sus datos
(`reshape`/`flatten`), o juntar varios arrays en uno solo
(`concatenate`/`vstack`/`hstack`).

### 🎈 Analogía sencilla

`reshape` es como tener 12 fichas de dominó en fila y reorganizarlas en una
cuadrícula de 3x4, sin tirar ni añadir ninguna ficha — solo cambia cómo están
colocadas. Combinar arrays es como pegar dos hojas de Excel, una debajo de la
otra, o una al lado de la otra.

### 🐍 Código Python


In [17]:
numeros = np.arange(12)
print("Array original (1D):", numeros)

numeros_en_tabla = numeros.reshape(3, 4)
print("Reorganizado en 3 filas x 4 columnas:")
print(numeros_en_tabla)

print("Aplanado de nuevo a 1D:", numeros_en_tabla.flatten())


Array original (1D): [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reorganizado en 3 filas x 4 columnas:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Aplanado de nuevo a 1D: [ 0  1  2  3  4  5  6  7  8  9 10 11]


In [18]:
ventas_norte = np.array([100, 200, 150])
ventas_sur = np.array([80, 120, 90])

todo_seguido = np.concatenate([ventas_norte, ventas_sur])
una_debajo_otra = np.vstack([ventas_norte, ventas_sur])
una_al_lado_otra = np.hstack([ventas_norte, ventas_sur])

print("concatenate:", todo_seguido)
print("vstack (apiladas como filas):")
print(una_debajo_otra)
print("hstack (en una sola fila larga):", una_al_lado_otra)


concatenate: [100 200 150  80 120  90]
vstack (apiladas como filas):
[[100 200 150]
 [ 80 120  90]]
hstack (en una sola fila larga): [100 200 150  80 120  90]


### 🔍 Explicación línea a línea

- `numeros.reshape(3, 4)` → reorganiza los mismos 12 números en una tabla de 3
  filas y 4 columnas. El número total de elementos tiene que coincidir
  exactamente (3 × 4 = 12), o NumPy dará un error.
- `.flatten()` → el proceso contrario: convierte cualquier array, sea de las
  dimensiones que sea, en una sola fila.
- `np.concatenate([a, b])` → junta los arrays uno detrás de otro, como pegar dos
  listas.
- `np.vstack([a, b])` → los apila como filas distintas de una tabla (cada array
  se convierte en una fila).
- `np.hstack([a, b])` → los pega en horizontal, en una sola fila larga (igual
  que `concatenate` para arrays 1D).

### ⚠️ Error común

Intentar un `reshape` con un número de filas/columnas que no encaja con el
total de elementos (por ejemplo, `numeros.reshape(3, 5)` con solo 12 números)
da un error `ValueError: cannot reshape array of size 12 into shape (3,5)`.

### 💼 Aplicación profesional

Combinar arrays es lo que harás al juntar datos de distintas fuentes (ventas de
varias tiendas, datos de varios meses) antes de analizarlos juntos — el
equivalente de un `UNION` en SQL o de apilar tablas en Power Query.


## 11. Ordenar datos

**Qué es:** poner los elementos de un array en orden, o saber **en qué orden
deberían colocarse** sin moverlos todavía.

### 🎈 Analogía sencilla

`sort` es ordenar una fila de cartas de menor a mayor. `argsort` es como
apuntar en un papel "para ordenarlas, primero pondría la carta que está en la
posición 3, luego la de la posición 0..." sin tocar las cartas todavía.

### 🐍 Código Python


In [19]:
ventas_dia = np.array([120, 45, 300, 80, 15])

ordenado = np.sort(ventas_dia)
posiciones_para_ordenar = np.argsort(ventas_dia)

print("Original:", ventas_dia)
print("Ordenado:", ordenado)
print("Posiciones que darían el orden:", posiciones_para_ordenar)


Original: [120  45 300  80  15]
Ordenado: [ 15  45  80 120 300]
Posiciones que darían el orden: [4 1 3 0 2]


### 🔍 Explicación línea a línea

- `np.sort(array)` → devuelve un **nuevo** array ya ordenado de menor a mayor
  (no modifica el original).
- `np.argsort(array)` → en vez de los valores, te da las **posiciones**: "el
  valor más pequeño está en la posición 4, el siguiente en la posición 1...".
  Esto es muy útil cuando tienes varios arrays relacionados (por ejemplo,
  nombres de productos y sus ventas) y quieres ordenar uno usando el orden de
  otro.

### 💼 Aplicación profesional

`argsort` es la base de un "Top N" — por ejemplo, ordenar productos por ventas
y quedarte con los nombres de los 3 más vendidos, usando las posiciones de
`argsort` para mirar también en el array de nombres.


## 12. Números aleatorios para simulación y muestreo

**Qué es:** generar números al azar, pero de forma controlada (puedes fijar una
"semilla" para que el azar sea siempre el mismo si lo necesitas repetir).

### 🎈 Analogía sencilla

`np.random.seed(42)` es como anotar en qué posición exacta empieza a barajar la
máquina de bingo. Si todo el mundo usa la misma semilla, a todos les van a
salir los mismos números "aleatorios" — útil para que tus pruebas sean
repetibles.

### 🐍 Código Python


In [20]:
np.random.seed(42)

enteros_al_azar = np.random.randint(0, 100, size=5)
decimales_uniformes = np.random.rand(5)
distribucion_normal = np.random.normal(loc=100, scale=15, size=5)

print("Enteros al azar (0-99):", enteros_al_azar)
print("Decimales uniformes (0-1):", decimales_uniformes)
print("Distribución normal (media=100, desv=15):", distribucion_normal)


Enteros al azar (0-99): [51 92 14 71 60]
Decimales uniformes (0-1): [0.59685016 0.44583275 0.09997492 0.45924889 0.33370861]
Distribución normal (media=100, desv=15): [105.88869626  86.06223    101.19747718  97.60725248 100.3333274 ]


### 🔍 Explicación línea a línea

- `np.random.seed(42)` → fija el punto de partida del generador aleatorio. El
  número `42` no tiene ningún significado especial, es solo una convención muy
  usada; podrías poner cualquier número.
- `np.random.randint(0, 100, size=5)` → 5 números enteros al azar entre 0
  (incluido) y 100 (excluido).
- `np.random.rand(5)` → 5 números decimales al azar entre 0 y 1, todos con la
  misma probabilidad.
- `np.random.normal(loc=100, scale=15, size=5)` → 5 números que siguen una
  distribución normal (campana de Gauss) centrada en `100`, con una dispersión
  (desviación estándar) de `15`. Es la distribución típica para simular datos
  "naturales" (alturas, tiempos, ventas con variación aleatoria).

### 💼 Aplicación profesional

Generar datos aleatorios es muy útil para crear datos de prueba antes de tener
datos reales, para simular escenarios (¿qué pasaría si las ventas variaran así?)
o para hacer muestreo aleatorio de un conjunto de datos muy grande sin tener que
procesarlo entero.


## 13. Resumen

| Concepto | Para qué sirve |
|---|---|
| `np.array()` | Crear un array a partir de una lista |
| `.shape`, `.ndim`, `.dtype`, `.size` | Conocer la forma y el tipo de un array |
| `np.zeros`, `np.ones`, `np.arange`, `np.linspace` | Generar arrays automáticamente |
| `array[fila, columna]` | Indexar y recortar arrays en 2D |
| `+ - * /` entre arrays | Operaciones vectorizadas, elemento a elemento |
| Broadcasting | Combinar un array con un valor o array más pequeño |
| `.sum()`, `.mean()`, `axis=` | Agregaciones, por fila o por columna |
| `array[condición]`, `np.where()` | Filtrar y clasificar datos |
| `np.nan`, `np.nanmean()` | Tratar datos faltantes |
| `reshape`, `concatenate`, `vstack`, `hstack` | Reorganizar y combinar arrays |
| `np.sort()`, `np.argsort()` | Ordenar datos |
| `np.random` | Generar datos aleatorios para simulación |

### 🔜 Por qué esto importa para lo que viene después

Pandas (tu próxima parada) está construido **encima** de NumPy: cada columna de
un DataFrame de Pandas es, por dentro, un array de NumPy con una etiqueta
puesta. Todo lo que has aprendido aquí — operaciones vectorizadas, `axis`,
boolean masking, `NaN` — lo vas a volver a ver con otro nombre en Pandas, pero
con la misma lógica de fondo. Por eso merece la pena tenerlo bien asentado antes
de seguir.


## 14. Ejercicios prácticos

Intenta cada ejercicio tú primero en la celda marcada. Después comprueba con la
solución. Todos están pensados con el sombrero de analista de datos puesto.

---

### 📝 Ejercicio 1 (básico) — Estadísticas de ventas semanales

Crea un array con las ventas de 7 días: `[120, 85, 200, 60, 150, 95, 175]`.
Calcula e imprime: la media, el máximo, el mínimo y la desviación estándar.


In [21]:
# Ejercicio 1 — Tu código aquí
ventas_semana = None  # crea aquí el array

# Calcula e imprime media, máximo, mínimo y desviación estándar


#### 💡 Solución — Ejercicio 1


In [22]:
ventas_semana = np.array([120, 85, 200, 60, 150, 95, 175])

print("Media:", ventas_semana.mean())
print("Máximo:", ventas_semana.max())
print("Mínimo:", ventas_semana.min())
print("Desviación estándar:", round(ventas_semana.std(), 2))


Media: 126.42857142857143
Máximo: 200
Mínimo: 60
Desviación estándar: 47.03


---

### 📝 Ejercicio 2 (intermedio) — Totales por producto y por mes

Tienes esta matriz de ventas (filas = productos, columnas = meses):

```
            enero  febrero  marzo
Mesa     [    120,      85,   200 ]
Silla    [     60,     150,    90 ]
Lámpara  [     35,      20,    10 ]
```

Crea la matriz y calcula: el total de cada producto (sumando sus 3 meses) y el
total de cada mes (sumando los 3 productos). Usa el parámetro `axis` correcto
para cada caso.


In [23]:
# Ejercicio 2 — Tu código aquí
ventas = None  # crea aquí la matriz 3x3

# Calcula total por producto y total por mes


#### 💡 Solución — Ejercicio 2


In [24]:
ventas = np.array([
    [120, 85, 200],
    [60, 150, 90],
    [35, 20, 10],
])

total_por_producto = ventas.sum(axis=1)
total_por_mes = ventas.sum(axis=0)

print("Total por producto:", total_por_producto)
print("Total por mes:", total_por_mes)


Total por producto: [405 300  65]
Total por mes: [215 255 300]


---

### 📝 Ejercicio 3 (intermedio) — Filtrar productos por encima de un umbral

Tienes este array de precios: `[15, 120, 45, 300, 8, 95, 210]`. Usa boolean
masking para quedarte solo con los precios mayores que `50`, y muestra también
cuántos precios cumplen esa condición.


In [25]:
# Ejercicio 3 — Tu código aquí
precios = None  # crea aquí el array

# Filtra los precios mayores que 50 y cuenta cuántos hay


#### 💡 Solución — Ejercicio 3


In [26]:
precios = np.array([15, 120, 45, 300, 8, 95, 210])

mascara = precios > 50
precios_filtrados = precios[mascara]

print("Precios mayores que 50:", precios_filtrados)
print("Cuántos cumplen la condición:", mascara.sum())


Precios mayores que 50: [120 300  95 210]
Cuántos cumplen la condición: 4


> 💡 Pista de por qué `mascara.sum()` funciona: en NumPy, `True` se comporta
> como `1` y `False` como `0` al sumarlos, así que sumar un array de
> `True`/`False` es lo mismo que contar cuántos `True` hay.

---

### 📝 Ejercicio 4 (intermedio-avanzado) — Clasificar ventas con `np.where`

Tienes el array de ventas semanales del Ejercicio 1. Calcula la media del
array, y después crea un nuevo array de etiquetas que diga `"Por encima de la
media"` para los días que superen la media, y `"Por debajo de la media"` para
el resto. Usa `np.where()`.


In [27]:
# Ejercicio 4 — Tu código aquí
ventas_semana = np.array([120, 85, 200, 60, 150, 95, 175])

media = None  # calcula la media

etiquetas = None  # usa np.where aquí


#### 💡 Solución — Ejercicio 4


In [28]:
ventas_semana = np.array([120, 85, 200, 60, 150, 95, 175])

media = ventas_semana.mean()
etiquetas = np.where(ventas_semana > media, "Por encima de la media", "Por debajo de la media")

print("Media:", media)
print("Etiquetas:", etiquetas)


Media: 126.42857142857143
Etiquetas: ['Por debajo de la media' 'Por debajo de la media'
 'Por encima de la media' 'Por debajo de la media'
 'Por encima de la media' 'Por debajo de la media'
 'Por encima de la media']


---

### 📝 Ejercicio 5 (reto) — Datos faltantes en una simulación

Usando `np.random.seed(7)`, genera un array de 10 "ventas diarias" con
`np.random.normal(loc=200, scale=30, size=10)`. Después, simula que los días en
las posiciones `2` y `6` no tienen dato (asígnales `np.nan`). Calcula e imprime:

1. La media usando `.mean()` normal (verás el problema).
2. La media usando `np.nanmean()` (la correcta).
3. Cuántos valores son `NaN`, usando `np.isnan()` y `.sum()`.


In [29]:
# Ejercicio 5 — Tu código aquí
np.random.seed(7)
ventas_diarias = None  # genera el array con distribución normal

# Asigna np.nan a las posiciones 2 y 6

# Calcula y muestra los 3 puntos pedidos


#### 💡 Solución — Ejercicio 5


In [30]:
np.random.seed(7)
ventas_diarias = np.random.normal(loc=200, scale=30, size=10)

ventas_diarias[2] = np.nan
ventas_diarias[6] = np.nan

print("Ventas diarias (con huecos):", np.round(ventas_diarias, 1))
print("Media normal (incorrecta):", ventas_diarias.mean())
print("Media ignorando huecos (correcta):", round(np.nanmean(ventas_diarias), 2))
print("Cantidad de valores NaN:", np.isnan(ventas_diarias).sum())


Ventas diarias (con huecos): [250.7 186.    nan 212.2 176.3 200.1   nan 147.4 230.5 218. ]
Media normal (incorrecta): nan
Media ignorando huecos (correcta): 202.66
Cantidad de valores NaN: 2


---

## 🔜 Próximos pasos

Con esto tienes una base sólida de NumPy. El siguiente paso natural en tu hoja
de ruta es **Pandas**, donde vas a usar `Series` y `DataFrame` — pero ahora ya
sabes que, por debajo, son arrays de NumPy con nombres de fila y columna
puestos encima. Dime cuándo quieres seguir con eso.
